/**
 * Turns the auth split PNG sources into a progressive set: tiny LQIP (data URI)
 * plus AVIF / WebP / progressive JPEG. Runs from `npm run build` / `dev` and
 * from the Vite plugin when a source file changes.
 *
 * Sources (replace a PNG and rebuild):
 *   assets/auth/pware-bg.png       — light templates (`*-light`: Corporate, Nord, …)
 *   assets/auth/pware-bg-dark.png  — dark templates (`*-dark`: Classic, Sunset, …)
 */
import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const here = dirname(fileURLToPath(import.meta.url))
export const uiRoot = join(here, '..')
export const authSourceDir = join(uiRoot, 'assets', 'auth')
const publicDir = join(uiRoot, 'public', 'auth')
const genFile = join(uiRoot, 'src', 'assets', 'auth', 'bg.gen.ts')
const stampFile = join(authSourceDir, '.stamp')

const VARIANTS = [
  { id: 'light', file: 'pware-bg.png', out: 'pware-bg' },
  { id: 'dark', file: 'pware-bg-dark.png', out: 'pware-bg-dark' },
]

async function fileHash(path) {
  const buf = await readFile(path)
  return createHash('sha256').update(buf).digest('hex')
}

async function sourceState() {
  const state = {}
  for (const variant of VARIANTS) {
    const path = join(authSourceDir, variant.file)
    try {
      state[variant.id] = await fileHash(path)
    } catch (err) {
      if (err && err.code === 'ENOENT') {
        state[variant.id] = null
        continue
      }
      throw err
    }
  }
  return state
}

function assetsBlock(out, lqip) {
  return `{
  lqip: ${JSON.stringify(lqip)},
  avif: ${JSON.stringify(`/auth/${out}.avif`)},
  webp: ${JSON.stringify(`/auth/${out}.webp`)},
  jpg: ${JSON.stringify(`/auth/${out}.jpg`)},
}`
}

async function emitVariant(variant, srcPath) {
  const pipeline = sharp(srcPath).rotate()
  const meta = await pipeline.metadata()
  const width = Math.min(meta.width ?? 1920, 1920)
  const sized = pipeline.resize({ width, withoutEnlargement: true })

  const lqipBuf = await sharp(srcPath)
    .rotate()
    .resize({ width: 32 })
    .webp({ quality: 28 })
    .toBuffer()

  await Promise.all([
    sized.clone().avif({ quality: 42, effort: 4 }).toFile(join(publicDir, `${variant.out}.avif`)),
    sized.clone().webp({ quality: 68 }).toFile(join(publicDir, `${variant.out}.webp`)),
    sized
      .clone()
      .jpeg({ quality: 72, progressive: true, mozjpeg: true })
      .toFile(join(publicDir, `${variant.out}.jpg`)),
  ])

  return `data:image/webp;base64,${lqipBuf.toString('base64')}`
}

export async function prepareAuthBg({ force = false } = {}) {
  const state = await sourceState()
  if (!state.light) {
    throw new Error(`missing ${join(authSourceDir, 'pware-bg.png')}`)
  }

  await mkdir(publicDir, { recursive: true })
  await mkdir(dirname(genFile), { recursive: true })

  if (!force) {
    try {
      const prev = JSON.parse(await readFile(stampFile, 'utf8'))
      if (prev.light === state.light && prev.dark === state.dark) {
        return { skipped: true, state }
      }
    } catch {
      // First run or a stale stamp.
    }
  }

  const lightLqip = await emitVariant(VARIANTS[0], join(authSourceDir, VARIANTS[0].file))
  let darkBlock = 'null'
  if (state.dark) {
    const darkLqip = await emitVariant(VARIANTS[1], join(authSourceDir, VARIANTS[1].file))
    darkBlock = assetsBlock(VARIANTS[1].out, darkLqip)
  }

  const ts = `// Generated by scripts/prepare-auth-bg.mjs — do not edit.
export type AuthBgAssets = {
  lqip: string
  avif: string
  webp: string
  jpg: string
}

export const authBgLight: AuthBgAssets = ${assetsBlock(VARIANTS[0].out, lightLqip)}

export const authBgDark: AuthBgAssets | null = ${darkBlock}
`

  await writeFile(genFile, ts)
  await writeFile(stampFile, JSON.stringify(state, null, 2) + '\n')
  return { skipped: false, state }
}

const invoked = process.argv[1]?.replaceAll('\\', '/').endsWith('prepare-auth-bg.mjs')
if (invoked) {
  prepareAuthBg().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
