// Code generated by go run ./internal/orgplan/gencatalog; DO NOT EDIT.

export const PLAN_ORDER = ["free", "starter", "team", "enterprise"] as const;

export type PlanSlug = (typeof PLAN_ORDER)[number];

export type PlanCharge = {
  kind: "free" | "usd" | "contact";
  usd: number;
  perPerson: boolean;
};

export type PlanLimits = {
  projects: number;
  workersPerProject: number;
  people: number;
  idleDays: number;
  logDays: number;
};

export type PlanConfig = {
  selfServe: boolean;
  charge: PlanCharge;
  themeFamily: "default" | "enterprise";
  limits: PlanLimits;
};

export const PLAN_BY_SLUG: Record<PlanSlug, PlanConfig> = {
  "free": {
    "selfServe": true,
    "charge": {
      "kind": "free",
      "usd": 0,
      "perPerson": false
    },
    "themeFamily": "default",
    "limits": {
      "projects": 1,
      "workersPerProject": 2,
      "people": 1,
      "idleDays": 60,
      "logDays": 7
    }
  },
  "starter": {
    "selfServe": true,
    "charge": {
      "kind": "usd",
      "usd": 5,
      "perPerson": true
    },
    "themeFamily": "default",
    "limits": {
      "projects": 2,
      "workersPerProject": 3,
      "people": 0,
      "idleDays": 0,
      "logDays": 0
    }
  },
  "team": {
    "selfServe": true,
    "charge": {
      "kind": "usd",
      "usd": 5,
      "perPerson": true
    },
    "themeFamily": "default",
    "limits": {
      "projects": 5,
      "workersPerProject": 5,
      "people": 0,
      "idleDays": 0,
      "logDays": 0
    }
  },
  "enterprise": {
    "selfServe": false,
    "charge": {
      "kind": "contact",
      "usd": 0,
      "perPerson": false
    },
    "themeFamily": "enterprise",
    "limits": {
      "projects": 0,
      "workersPerProject": 0,
      "people": 0,
      "idleDays": 0,
      "logDays": 0
    }
  }
};

export const PERSON_USD = 5;
