// Code generated by cmd/namesgen from names/names.yaml. DO NOT EDIT.

package id

// The five planes, in the order names.yaml gives them.
const (
	ContextHub     Context = "hub"
	ContextProject Context = "project"
	ContextGDesk   Context = "gdesk"
	ContextFleet   Context = "fleet"
	ContextWorker  Context = "worker"
)

// contexts backs Contexts(). Order is the ontology's, not sorted.
var contexts = []Context{ContextHub, ContextProject, ContextGDesk, ContextFleet, ContextWorker}

// Entity prefixes. Each one is the last segment of its entity's qualified
// name, derived rather than declared, so the two cannot drift apart.
const (
	Attachment     Kind = "attachment"
	Device         Kind = "device"
	Enrollment     Kind = "enrollment"
	Host           Kind = "host"
	Terminal       Kind = "terminal"
	Conversation   Kind = "conversation"
	Stream         Kind = "stream"
	Surface        Kind = "surface"
	Turn           Kind = "turn"
	Utterance      Kind = "utterance"
	Account        Kind = "account"
	Command        Kind = "command"
	Event          Kind = "event"
	Folder         Kind = "folder"
	Gateway        Kind = "gateway"
	Mail           Kind = "mail"
	Org            Kind = "org"
	Invite         Kind = "org_invite"
	Reset          Kind = "password_reset"
	Project        Kind = "project"
	Staff          Kind = "staff"
	Token          Kind = "token"
	Attention      Kind = "attention"
	Bridge         Kind = "bridge"
	Draft          Kind = "draft"
	Evidence       Kind = "evidence"
	ForeignProject Kind = "foreign_project"
	MCPServer      Kind = "mcp_server"
	Member         Kind = "member"
	Persona        Kind = "persona"
	Proof          Kind = "proof"
	Repo           Kind = "repo"
	Run            Kind = "run"
	Secret         Kind = "secret"
	Task           Kind = "task"
	Thread         Kind = "thread"
	Todo           Kind = "todo"
	Work           Kind = "work"
	Coder          Kind = "coder"
	Workspace      Kind = "workspace"
)

// entities maps each prefix to its described entity. Registration is what
// makes a prefix real: New and Parse both reject anything absent here.
var entities = map[Kind]Spec{
	Attachment: {
		Name:        "initagent.fleet.attachment",
		Context:     ContextFleet,
		Description: "One browser view of a terminal. It exists so \"who is watching this session\" is answerable, and so closing a tab does not kill the process behind it.",
		Lifetime:    "while the tab is open",
	},
	Device: {
		Name:        "initagent.fleet.device",
		Context:     ContextFleet,
		Description: "One enrolled connector instance — what upstream called an agent. It holds the socket to the gateway and it is what a task is placed on.",
		Lifetime:    "enroll → delete",
	},
	Enrollment: {
		Name:        "initagent.fleet.enrollment",
		Context:     ContextFleet,
		Description: "The single-use credential that joins a machine. Separate from the device so handing someone an enrolment is not handing them a machine that already exists.",
		Lifetime:    "minted → used or expired",
	},
	Host: {
		Name:        "initagent.fleet.host",
		Context:     ContextFleet,
		Description: "One physical machine. Two connectors on one box are two devices sharing a host, and the scheduler needs the difference because CPU and per-machine coding-CLI authentication belong to the host.",
		Lifetime:    "first enroll → last device removed",
	},
	Terminal: {
		Name:        "initagent.fleet.terminal",
		Context:     ContextFleet,
		Description: "One process host — a tmux session, a ConPTY, a bare pty. The backend is a declared capability rather than an assumption, which is what keeps Windows from being a special case in every code path.",
		Lifetime:    "until killed or host reboot",
	},
	Conversation: {
		Name:        "initagent.gdesk.conversation",
		Context:     ContextGDesk,
		Description: "One person's ongoing talk at the desk, and the scope of both the floor and the transcripts. Sharing either across people would route one person's unnamed sentence to somebody else's addressee, with nothing in a log.",
		Lifetime:    "walk-up → goodbye",
	},
	Stream: {
		Name:        "initagent.gdesk.stream",
		Context:     ContextGDesk,
		Description: "One glass's numbered view of the seam. Each connection keeps its own log, so each device detects its own gaps and resumes on its own rather than sharing a cursor with the others.",
		Lifetime:    "while the glass is connected",
	},
	Surface: {
		Name:        "initagent.gdesk.surface",
		Context:     ContextGDesk,
		Description: "A window in the glass. A reply travels as one — it opens, text arrives in it a piece at a time — rather than as a verb of its own, so the glass has one thing to render and one thing to fail.",
		Lifetime:    "opened → closed",
	},
	Turn: {
		Name:        "initagent.gdesk.turn",
		Context:     ContextGDesk,
		Description: "One segment of one utterance being answered by one staff member. A sentence addressed to two people is two turns, so the answer keys here and not on the utterance. This entity is the reason the abbreviated prefixes were dropped: `tur-`, `trn-` and `trm-` were three spellings of two entities, and telling them apart in a log needed the table open. `turn-` and `terminal-` need nothing.",
		Lifetime:    "one answer",
	},
	Utterance: {
		Name:        "initagent.gdesk.utterance",
		Context:     ContextGDesk,
		Description: "One thing said to the staff: one press-and-release, or one textarea submit. The glass mints it once and reuses it on every retry, which is the only thing that makes a re-delivery recognisable as one.",
		Lifetime:    "one message",
	},
	Account: {
		Name:        "initagent.hub.account",
		Context:     ContextHub,
		Description: "A person who can sign in. Memberships, tokens and audit all point at one of these rather than at an email string, so changing an address is not changing an identity.",
		Lifetime:    "until deleted",
	},
	Command: {
		Name:        "initagent.hub.command",
		Context:     ContextHub,
		Description: "One instruction on the hub's outbox, waiting for the device or gateway that must run it to acknowledge. The glass seam has a second thing called a command; the naming ontology keeps this prefix and renames that one.",
		Lifetime:    "until acked",
	},
	Event: {
		Name:        "initagent.hub.event",
		Context:     ContextHub,
		Description: "One ingested fact on the hub's stream — what the cockpit subscribes to and what an operator reads back. A feed rather than the store of record, which is why it expires.",
		Lifetime:    "retention window",
	},
	Folder: {
		Name:        "initagent.hub.folder",
		Context:     ContextHub,
		Description: "A display grouping over projects, nested by parent_id, with a project carrying a nullable folder_id. It earns an identifier rather than a path string because a path makes the name the identity and breaks on the first rename. Nothing inherits through one — no role, no secret, no catalogue row — because folder inheritance is still undecided on purpose.",
		Lifetime:    "until deleted",
	},
	Gateway: {
		Name:        "initagent.hub.gateway",
		Context:     ContextHub,
		Description: "One running gateway instance. Projects are isolated per gateway, so which gateway holds a project is a placement the hub has to record rather than derive.",
		Lifetime:    "provisioned → torn down",
	},
	Mail: {
		Name:        "initagent.hub.mail",
		Context:     ContextHub,
		Description: "One outbound message on the mail outbox. Queued as a row so a provider outage delays an invitation or a password reset instead of losing it.",
		Lifetime:    "until sent or dead",
	},
	Org: {
		Name:        "initagent.hub.org",
		Context:     ContextHub,
		Description: "A customer's organization: the billing boundary, the member list, and the scope every query narrows by. Real from day one so there is no \"add tenancy later\" branch.",
		Lifetime:    "until deleted",
	},
	Invite: {
		Name:        "initagent.hub.org_invite",
		Context:     ContextHub,
		Description: "One invitation to join an organization. It exists before the invitee has an account, so it cannot yet be a membership row.",
		Lifetime:    "until used, revoked, or expired",
	},
	Reset: {
		Name:        "initagent.hub.password_reset",
		Context:     ContextHub,
		Description: "One password-reset grant. Single use and time-boxed, which is why it is a row that can be burned rather than a signed value that cannot.",
		Lifetime:    "until used or expired",
	},
	Project: {
		Name:        "initagent.hub.project",
		Context:     ContextHub,
		Description: "The hub's catalogue entry for one project. The gateway receives this same value at provisioning and uses it as its own project id, so one identifier deliberately spans two planes.",
		Lifetime:    "project lifetime",
	},
	Staff: {
		Name:        "initagent.hub.staff",
		Context:     ContextHub,
		Description: "One virtual being who works for the organization: greets at a glass, directs the work that follows, wears a rendered body on a scene, and sits on the People screen with a badge. The home is `hub` and not `gdesk` because the desk is one of his posts rather than who he is — his Big Five baseline and his voice identity are held on the hub so they survive any machine, and the People screen is a hub screen. That the code addressing him lives in internal/gdesk is not a contradiction: a context is a vocabulary domain and not a storage location, the same way a `fleet` device row lives on the gateway.",
		Lifetime:    "until removed",
	},
	Token: {
		Name:        "initagent.hub.token",
		Context:     ContextHub,
		Description: "An API credential carrying a boundary and a verb set, deliberately narrower than the person who minted it. The row holds the scopes and a hash; the secret itself is never stored.",
		Lifetime:    "until revoked",
	},
	Attention: {
		Name:        "initagent.project.attention",
		Context:     ContextProject,
		Description: "A pending human decision: a review to sign off, an ambiguity a run could not resolve. A row rather than a notification, so nothing waits on somebody invisibly.",
		Lifetime:    "opened → answered or dismissed",
	},
	Bridge: {
		Name:        "initagent.project.bridge",
		Context:     ContextProject,
		Description: "One recorded correspondence between two elements that are not permanently one to one — our project and a tool's project, our task and a foreign issue.",
		Lifetime:    "while both sides exist",
	},
	Draft: {
		Name:        "initagent.project.draft",
		Context:     ContextProject,
		Description: "A pre-plan note: something worth keeping before anybody decided it is work. It becomes a todo or it is dropped; it never dispatches.",
		Lifetime:    "until promoted or dropped",
	},
	Evidence: {
		Name:        "initagent.project.evidence",
		Context:     ContextProject,
		Description: "One captured artefact of a run — a diff, a log, an output file. Produced on the worker and durable on the gateway, which is why it is filed under project and not worker: durability decides the context.",
		Lifetime:    "retention window",
	},
	ForeignProject: {
		Name:        "initagent.project.foreign_project",
		Context:     ContextProject,
		Description: "Our surrogate for a project some tool mints itself. The correspondence to our project is many-to-many and the foreign identifier can change under us, which is why it is a row and not a column.",
		Lifetime:    "while the foreign project is referenced",
	},
	MCPServer: {
		Name:        "initagent.project.mcp_server",
		Context:     ContextProject,
		Description: "One MCP server in the project's catalogue, with the audience — hub inbound or harness on the worker — that decides where it may be reached.",
		Lifetime:    "until removed",
	},
	Member: {
		Name:        "initagent.project.member",
		Context:     ContextProject,
		Description: "One person's membership of one project, carrying the role that project enforces. Separate from org membership because the two boundaries answer different questions.",
		Lifetime:    "until removed",
	},
	Persona: {
		Name:        "initagent.project.persona",
		Context:     ContextProject,
		Description: "A virtual AI staff member on a project: the actor a task is attributed to, as against the account that requested it. Not an IAM role, and not OMO's persona files.",
		Lifetime:    "until removed",
	},
	Proof: {
		Name:        "initagent.project.proof",
		Context:     ContextProject,
		Description: "A verdict over evidence: the reviewed answer to whether a run did what it claimed. Permanent, so a later rerun cannot quietly replace the judgement that was made.",
		Lifetime:    "permanent",
	},
	Repo: {
		Name:        "initagent.project.repo",
		Context:     ContextProject,
		Description: "The repository a project's work lands in, and the base every pull request opens against. A device pushing to a fork keeps its own URL as a field rather than a second repo row.",
		Lifetime:    "until unbound",
	},
	Run: {
		Name:        "initagent.project.run",
		Context:     ContextProject,
		Description: "One attempt at a task on one machine. A retry elsewhere is a new run under the same task, so a task's history is a list rather than an overwritten status.",
		Lifetime:    "one execution",
	},
	Secret: {
		Name:        "initagent.project.secret",
		Context:     ContextProject,
		Description: "A recoverable provider secret held for the project — a database DSN, a provider key. Recoverable rather than hashed, because the worker has to present it to something else.",
		Lifetime:    "until rotated",
	},
	Task: {
		Name:        "initagent.project.task",
		Context:     ContextProject,
		Description: "One dispatchable unit of work. It names a requester (`account-`) and an actor (`persona-`), which is what makes a result attributable to somebody rather than to the installation.",
		Lifetime:    "queued → done",
	},
	Thread: {
		Name:        "initagent.project.thread",
		Context:     ContextProject,
		Description: "Our surrogate for a conversation owned by a harness (OpenCode, Codex, Cursor). We mint the identifier and the foreign coordinates are its payload, so a provider reshaping its own ids cannot break our references.",
		Lifetime:    "while the foreign thread is referenced",
	},
	Todo: {
		Name:        "initagent.project.todo",
		Context:     ContextProject,
		Description: "One checklist item: the intent, not the execution. A todo maps to many tasks over time — retry, split, rework after a rejected review — so the intent survives a failed attempt.",
		Lifetime:    "until done or dropped",
	},
	Work: {
		Name:        "initagent.project.work",
		Context:     ContextProject,
		Description: "A plan-scoped umbrella over the tasks one plan produced, so progress on a plan is answerable without the tasks having to know about each other.",
		Lifetime:    "plan lifetime",
	},
	Coder: {
		Name:        "initagent.worker.coder",
		Context:     ContextWorker,
		Description: "One coder CLI process: the LLM actually doing the work, which the industry calls an agent and this vocabulary bans us from calling that. Its kind and its host are closed enumerations, so a headless coder needs no terminal row.",
		Lifetime:    "process lifetime",
	},
	Workspace: {
		Name:        "initagent.worker.workspace",
		Context:     ContextWorker,
		Description: "The worktree one run works in. Per run, so two runs on the same machine cannot see each other's half-finished edits.",
		Lifetime:    "per run",
	},
}

// unminted are the entities this vocabulary owns that this package does not
// mint an identifier for.
var unminted = []Spec{
	{
		Name:        "initagent.fleet.file",
		Context:     ContextFleet,
		Description: "A file on an enrolled machine's disk, listed, downloaded or uploaded through the connector. A device id and a path already name it; a row of ours would imply the hub holds something it does not.",
		Lifetime:    "the file's own",
	},
	{
		Name:        "initagent.hub.identity",
		Context:     ContextHub,
		Description: "One identity-provider subject linked to an account — a Google or a GitHub login. The provider owns the key, so the pair (provider, subject) identifies it and there is nothing for us to mint. It is a row rather than a column so one person can hold several logins.",
		Lifetime:    "until unlinked",
	},
	{
		Name:        "initagent.hub.preset",
		Context:     ContextHub,
		Description: "A saved command a person can run on a machine, seeded at first open and editable afterwards. It is stored on the hub, which is why it is a hub word even though what it runs is a fleet thing.",
		Lifetime:    "until deleted",
	},
	{
		Name:        "initagent.hub.template",
		Context:     ContextHub,
		Description: "One shipped create-project choice: a label over the delivery contract, whether a repo is required, and which worker capabilities the project needs. It is a catalogue in the binary, not a project.kind column.",
		Lifetime:    "ships with the binary",
	},
	{
		Name:        "initagent.hub.update",
		Context:     ContextHub,
		Description: "The installation's own release: which version runs, which is available, and how much of the fleet is behind. Operating the hub rather than using it, which is why no token can be granted it.",
		Lifetime:    "until superseded",
	},
	{
		Name:        "initagent.project.binding",
		Context:     ContextProject,
		Description: "The project's own row on the gateway, as against the hub's catalogue entry. It carries the `project-` the hub minted rather than one of its own: the correspondence is 1:1 for the life of the product, which is the one place the rule that every correspondence between elements is an explicit bridge row is deliberately narrowed to a shared identifier — the one prefix this vocabulary spells `project- (shared)`.",
		Lifetime:    "project lifetime",
		Borrows:     Project,
	},
}
