package orgplan

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"
)

// TypeScript is the generated module for site and cockpit. Copy (CTA,
// card names) stays in those apps; this file is structure and prices.
func TypeScript() string {
	return renderTS(Catalogue(), PersonUSD())
}

func renderTS(plans []Plan, personUSD int) string {
	slugs := make([]string, len(plans))
	for i, p := range plans {
		slugs[i] = string(p.ID)
	}
	var b strings.Builder
	b.WriteString("// Code generated by go run ./internal/orgplan/gencatalog; DO NOT EDIT.\n\n")
	b.WriteString("export const PLAN_ORDER = [")
	for i, slug := range slugs {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(&b, "%q", slug)
	}
	b.WriteString("] as const;\n\n")
	b.WriteString("export type PlanSlug = (typeof PLAN_ORDER)[number];\n\n")
	b.WriteString("export type PlanCharge = {\n")
	b.WriteString("  kind: \"free\" | \"usd\" | \"contact\";\n")
	b.WriteString("  usd: number;\n")
	b.WriteString("  perPerson: boolean;\n")
	b.WriteString("};\n\n")
	b.WriteString("export type PlanLimits = {\n")
	b.WriteString("  projects: number;\n")
	b.WriteString("  workersPerProject: number;\n")
	b.WriteString("  people: number;\n")
	b.WriteString("  idleDays: number;\n")
	b.WriteString("  logDays: number;\n")
	b.WriteString("};\n\n")
	b.WriteString("export type PlanConfig = {\n")
	b.WriteString("  selfServe: boolean;\n")
	b.WriteString("  charge: PlanCharge;\n")
	b.WriteString("  themeFamily: \"default\" | \"enterprise\";\n")
	b.WriteString("  limits: PlanLimits;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const PLAN_BY_SLUG: Record<PlanSlug, PlanConfig> = ")
	b.WriteString(marshalPlanObject(plans))
	b.WriteString(";\n\n")
	fmt.Fprintf(&b, "export const PERSON_USD = %d;\n", personUSD)
	return b.String()
}

func marshalPlanObject(plans []Plan) string {
	var b strings.Builder
	b.WriteString("{\n")
	for i, p := range plans {
		raw, err := json.Marshal(planYAML{
			SelfServe:   p.SelfServe,
			Charge:      p.Charge,
			ThemeFamily: p.ThemeFamily,
			Limits:      p.Limits,
		})
		if err != nil {
			panic(err)
		}
		var pretty bytes.Buffer
		if err := json.Indent(&pretty, raw, "  ", "  "); err != nil {
			panic(err)
		}
		fmt.Fprintf(&b, "  %q: %s", p.ID, pretty.Bytes())
		if i < len(plans)-1 {
			b.WriteByte(',')
		}
		b.WriteByte('\n')
	}
	b.WriteString("}")
	return b.String()
}
