package names

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"slices"
	"strconv"
	"strings"
)

// GoPackage is the package the generated registry belongs to.
const GoPackage = "id"

// RegenerateCommand is the one command that rewrites both artifacts. It is a
// string rather than a comment so a failing goldens test can name it.
const RegenerateCommand = "go generate ./internal/id"

// generatedBy is the first line of the generated Go file. `gopls`, `go vet` and
// every reviewer key on this exact shape.
const generatedBy = "// Code generated by cmd/namesgen from names/names.yaml. DO NOT EDIT."

// EmitGo renders the registry as the Go source `internal/id` compiles.
//
// It introduces no import: every value is a string literal or a constant this
// file also declares, which is what keeps `internal/id` a leaf.
//
// The long descriptions travel here and not into names.json. A reader who wants
// to know why `staff` is a hub word is reading Go or YAML, never a minified
// artifact in another language.
func EmitGo(r *Registry) ([]byte, error) {
	var b strings.Builder

	b.WriteString(generatedBy + "\n\n")
	b.WriteString("package " + GoPackage + "\n\n")

	b.WriteString("// The five planes, in the order names.yaml gives them.\n")
	b.WriteString("const (\n")
	for _, c := range r.Contexts {
		fmt.Fprintf(&b, "%s Context = %s\n", c.GoConst, strconv.Quote(c.Name))
	}
	b.WriteString(")\n\n")

	b.WriteString("// contexts backs Contexts(). Order is the ontology's, not sorted.\n")
	b.WriteString("var contexts = []Context{")
	for i, c := range r.Contexts {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(c.GoConst)
	}
	b.WriteString("}\n\n")

	b.WriteString("// Entity prefixes. Each one is the last segment of its entity's qualified\n")
	b.WriteString("// name, derived rather than declared, so the two cannot drift apart.\n")
	b.WriteString("const (\n")
	for _, e := range r.Minted() {
		fmt.Fprintf(&b, "%s Kind = %s\n", e.GoConst, strconv.Quote(e.Prefix()))
	}
	b.WriteString(")\n\n")

	b.WriteString("// entities maps each prefix to its described entity. Registration is what\n")
	b.WriteString("// makes a prefix real: New and Parse both reject anything absent here.\n")
	b.WriteString("var entities = map[Kind]Spec{\n")
	for _, e := range r.Minted() {
		fmt.Fprintf(&b, "%s: {\n", e.GoConst)
		r.writeSpecFields(&b, e)
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// unminted are the entities this vocabulary owns that this package does not\n")
	b.WriteString("// mint an identifier for.\n")
	b.WriteString("var unminted = []Spec{\n")
	for _, e := range r.Unminted() {
		b.WriteString("{\n")
		r.writeSpecFields(&b, e)
		b.WriteString("},\n")
	}
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("names: generated Go does not parse: %w", err)
	}
	return out, nil
}

// writeSpecFields writes one Spec literal's body.
func (r *Registry) writeSpecFields(b *strings.Builder, e Entity) {
	fmt.Fprintf(b, "Name: %s,\n", strconv.Quote(e.Name))
	fmt.Fprintf(b, "Context: %s,\n", r.contextConst(e.Context))
	fmt.Fprintf(b, "Description: %s,\n", strconv.Quote(strings.TrimRight(e.Description, "\n")))
	fmt.Fprintf(b, "Lifetime: %s,\n", strconv.Quote(e.Lifetime))
	if e.Borrows != "" {
		fmt.Fprintf(b, "Borrows: %s,\n", r.mintingConst(e.Borrows))
	}
}

// mintingConst is the Go constant of whichever entity mints prefix.
func (r *Registry) mintingConst(prefix string) string {
	for _, e := range r.Entities {
		if e.Mints && e.Prefix() == prefix {
			return e.GoConst
		}
	}
	return ""
}

// jsonRegistry is names.json: every plane a consumer in another repository
// needs, and no prose.
type jsonRegistry struct {
	Schema              int          `json:"schema"`
	Authority           string       `json:"authority"`
	SeamEnvelopeVersion int          `json:"seamEnvelopeVersion"`
	Grammar             jsonGrammar  `json:"grammar"`
	Contexts            []string     `json:"contexts"`
	Entities            []jsonEntity `json:"entities"`
	Capabilities        []string     `json:"capabilities"`
	HappeningPrefixes   []string     `json:"happeningPrefixes"`
}

// jsonGrammar spells each plane's shape so a consumer assembles a name rather
// than pattern-matching one it saw somewhere.
type jsonGrammar struct {
	Entity     string `json:"entity"`
	Identifier string `json:"identifier"`
	Happening  string `json:"happening"`
	Permission string `json:"permission"`
	Separator  string `json:"separator"`
}

type jsonEntity struct {
	Name string `json:"name"`
	// Context and Entity are the two halves every derived name is built from.
	Context string `json:"context"`
	Entity  string `json:"entity"`
	// IdentifierPrefix includes the separator, so a consumer matches on it
	// directly. Empty when nothing mints an identifier for this entity.
	IdentifierPrefix string `json:"identifierPrefix"`
	Mints            bool   `json:"mints"`
	// Borrows names the entity whose prefix this row carries instead of one of
	// its own.
	Borrows         string   `json:"borrows,omitempty"`
	Lifetime        string   `json:"lifetime"`
	Capabilities    []string `json:"capabilities"`
	HappeningPrefix string   `json:"happeningPrefix"`
}

// EmitJSON renders the artifact that crosses a repository boundary.
//
// Sorted throughout, and a trailing newline, so a regeneration with no source
// change produces a byte-identical file.
func EmitJSON(r *Registry) ([]byte, error) {
	doc := jsonRegistry{
		Schema:              r.Schema,
		Authority:           r.Authority,
		SeamEnvelopeVersion: r.Seam.EnvelopeVersion,
		Grammar: jsonGrammar{
			Entity:     "<authority>.<context>.<entity>",
			Identifier: "<prefix>" + separator + "<uuidv7>",
			Happening:  "<context>.<entity>.<verb>",
			Permission: "<verb>:<context>.<entity>",
			Separator:  separator,
		},
		Contexts:          r.ContextNames(),
		Capabilities:      r.Capabilities(),
		HappeningPrefixes: happeningPrefixes(r),
	}
	if doc.Capabilities == nil {
		doc.Capabilities = []string{}
	}
	for _, e := range r.SortedEntities() {
		row := jsonEntity{
			Name:            e.Name,
			Context:         e.Context,
			Entity:          e.Prefix(),
			Mints:           e.Mints,
			Borrows:         e.Borrows,
			Lifetime:        e.Lifetime,
			Capabilities:    e.CapabilityNames(),
			HappeningPrefix: e.HappeningPrefix(),
		}
		if row.Capabilities == nil {
			row.Capabilities = []string{}
		}
		switch {
		case e.Mints:
			row.IdentifierPrefix = e.Prefix() + separator
		case e.Borrows != "":
			row.IdentifierPrefix = e.Borrows + separator
		}
		doc.Entities = append(doc.Entities, row)
	}

	// An Encoder rather than MarshalIndent, for SetEscapeHTML(false): the
	// grammar strings are angle-bracket placeholders, and `\u003c` in the one
	// file a consumer reads to learn the shape of a name is noise.
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		return nil, fmt.Errorf("names: names.json cannot be encoded: %w", err)
	}
	return buf.Bytes(), nil
}

// happeningPrefixes is every legal left-hand side of a happening name, sorted.
//
// A producer in another language reads this list to answer the only question
// that matters at the boundary: which words may stand in front of my verb. The
// sensing process that emitted `desk.people.changed` had no such list. It has
// one now: `pware-os-facts` keeps a pinned copy of this output and a test
// recomputes every kind it may emit against the pin, which is how that string
// became `gdesk.attendance.changed`.
func happeningPrefixes(r *Registry) []string {
	out := make([]string, 0, len(r.Entities))
	for _, e := range r.Entities {
		out = append(out, e.HappeningPrefix())
	}
	slices.Sort(out)
	return slices.Compact(out)
}
